export enum PaymentStatus {
  PENDING = 'pending',
  PROCESSED = 'processed',
  FAILED = 'failed',
}

export enum ProcessorType {
  DEFAULT = 'default',
  FALLBACK = 'fallback',
}

export enum ErrorCode {
  PAYMENT_ALREADY_EXISTS = 'PAYMENT_ALREADY_EXISTS',
  INVALID_CORRELATION_ID = 'INVALID_CORRELATION_ID',
  INVALID_AMOUNT = 'INVALID_AMOUNT',
  PAYMENT_PROCESSING_FAILED = 'PAYMENT_PROCESSING_FAILED',
  PROCESSOR_UNAVAILABLE = 'PROCESSOR_UNAVAILABLE',
  HEALTH_CHECK_RATE_LIMITED = 'HEALTH_CHECK_RATE_LIMITED',
  DATABASE_CONNECTION_ERROR = 'DATABASE_CONNECTION_ERROR',
  REDIS_CONNECTION_ERROR = 'REDIS_CONNECTION_ERROR',
  INVALID_DATE_RANGE = 'INVALID_DATE_RANGE',
}

export enum HttpStatusCode {
  OK = 200,
  CREATED = 201,
  BAD_REQUEST = 400,
  CONFLICT = 409,
  TOO_MANY_REQUESTS = 429,
  INTERNAL_SERVER_ERROR = 500,
  SERVICE_UNAVAILABLE = 503,
}